// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserInput } from "./UserInput";

/**
 * Spawn a child agent thread from an already loaded parent thread.
 */
export type ThreadSpawnParams = { threadId: string, input: Array<UserInput>,
/**
 * Optional relative task name for the child agent path.
 *
 * Omitted lets the server assign a unique path segment.
 */
taskName?: string | null, };
