// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Close a spawned child agent thread and its live descendants.
 */
export type ThreadCloseParams = { threadId: string, };
